# Generated by Django 2.2.5 on 2019-09-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ('-hire_date',)},
        ),
    ]
